apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: medicure
          image: sailanadh123/medicure:1.0
          ports:
            - containerPort: 8082
