apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  selector:
    app: medicure
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30080
  type: NodePort
